version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Gradle and Docker"
      - chmod +x gradlew
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - echo Building Docker image...
      - docker build -t springboot-microservice .
      - docker tag springboot-microservice:latest public.ecr.aws/m2w3h1s9/springboot-microservice:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push public.ecr.aws/m2w3h1s9/springboot-microservice:latest
      - echo Writing image definitions...
      - printf '[{"name":"springboot-microservice","imageUri":"%s"}]'776743135642.dkr.us-east-1.amazonaws.com/springboot-microservice:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
